Updates to check for .NET Core compatibility
- Check for all multi-dimensional array types by checking the element type vs. using regex.
- Migrate all existing tests to NUnit
- Add tests for .NET Core apis that throw (appdomain/codedom)
- Compile for both net48 and net7.0-windows on Windows
- Add new warning return code
- Add option to check member access
- Added tests for all yak packages
- All test projects are now sdk-style so they compile with dotnet

Cite RH-72510

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,26 +1,13 @@
 #!/usr/bin/env bash
 
-# script/bootstrap: Resolve all dependencies that the application requires to
-#                   run.
+# script/bootstrap: Resolve all dependencies that the application requires to run.
 
 set -e
 
-cd "$(dirname "$0")/.."
-
-if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
-  #brew update
-
-  brew bundle check >/dev/null 2>&1  || {
-    echo "==> Installing Homebrew dependencies..."
-    brew bundle
-  }
+if ! [ -x "$(command -v dotnet)" ]; then
+  echo 'Error: .NET SDK (dotnet command) is not installed or found.  Install via https://dotnet.microsoft.com' >&2
+  exit 1
 fi
 
-# if ci + linux, try installing bats via npm
-if [ $CI ] && [ "$(uname -s)" = "Linux" ]; then
-  npm install bats
-fi
 
-# nuget
-echo "==> Installing NuGet dependencies..."
-nuget restore src/Compat.sln
+echo 'Everything is ready to go!'
